### ISSUE TITLE
This doesn't work on windows

### ISSUE THREAD

**Issue by EllaShar** [brwr/thinkster-django-angular-boilerplate#12]

**Comment by diecamdia** [comment]
This is the error when  i run the command python manage.py migrate on windows

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "d:\MisTrabajos\thinkster-djangular\lib\site-packages\django\core\management\__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "d:\MisTrabajos\thinkster-djangular\lib\site-packages\django\core\management\__init__.py", line 354, in execute
    django.setup()
  File "d:\MisTrabajos\thinkster-djangular\lib\site-packages\django\__init__.py", line 18, in setup
    from django.utils.log import configure_logging
  File "d:\MisTrabajos\thinkster-djangular\lib\site-packages\django\utils\log.py", line 13, in <module>
    from django.views.debug import ExceptionReporter, get_exception_reporter_filter
  File "d:\MisTrabajos\thinkster-djangular\lib\site-packages\django\views\debug.py", line 10, in <module>
    from django.http import (HttpResponse, HttpResponseServerError,
  File "d:\MisTrabajos\thinkster-djangular\lib\site-packages\django\http\__init__.py", line 4, in <module>
    from django.http.response import (HttpResponse, StreamingHttpResponse,
  File "d:\MisTrabajos\thinkster-djangular\lib\site-packages\django\http\response.py", line 13, in <module>
    from django.core.serializers.json import DjangoJSONEncoder
  File "d:\MisTrabajos\thinkster-djangular\lib\site-packages\django\core\serializers\__init__.py", line 23, in <module>
    from django.core.serializers.base import SerializerDoesNotExist
  File "d:\MisTrabajos\thinkster-djangular\lib\site-packages\django\core\serializers\base.py", line 6, in <module>
    from django.db import models
  File "d:\MisTrabajos\thinkster-djangular\lib\site-packages\django\db\models\__init__.py", line 6, in <module>
    from django.db.models.query import Q, QuerySet, Prefetch  # NOQA
  File "d:\MisTrabajos\thinkster-djangular\lib\site-packages\django\db\models\query.py", line 13, in <module>
    from django.db.models.fields import AutoField, Empty
  File "d:\MisTrabajos\thinkster-djangular\lib\site-packages\django\db\models\fields\__init__.py", line 18, in <module>
    from django import forms
  File "d:\MisTrabajos\thinkster-djangular\lib\site-packages\django\forms\__init__.py", line 6, in <module>
    from django.forms.fields import *  # NOQA
  File "d:\MisTrabajos\thinkster-djangular\lib\site-packages\django\forms\fields.py", line 18, in <module>
    from django.forms.utils import from_current_timezone, to_current_timezone
  File "d:\MisTrabajos\thinkster-djangular\lib\site-packages\django\forms\utils.py", line 15, in <module>
    from django.utils.html import format_html, format_html_join, escape
  File "d:\MisTrabajos\thinkster-djangular\lib\site-packages\django\utils\html.py", line 16, in <module>
    from .html_parser import HTMLParser, HTMLParseError
  File "d:\MisTrabajos\thinkster-djangular\lib\site-packages\django\utils\html_parser.py", line 12, in <module>
    HTMLParseError = _html_parser.HTMLParseError
AttributeError: module 'html.parser' has no attribute 'HTMLParseError'

**Comment by jattoabdul** [comment]
i get the same error above on my windows machine. any workaround this?

**Comment by dddjjjbbb** [comment]
Hi guys, please see the following http://stackoverflow.com/a/36000103

In my case I upgraded to 1.8, this solved my issue.
