### ISSUE TITLE
Cannot find module 'clone-stats'

### ISSUE THREAD

**Issue by EllaShar** [brwr/thinkster-django-angular-boilerplate#13]
Error: Cannot find module 'clone-stats'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Ella\Desktop\thinkster-django-angular-boiler
plate\node_modules\gulp-ng-annotate\node_modules\gulp-util\node_modules\vinyl\in
dex.js:3:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by GiselaKay** [comment]
Having the same error

**Comment by SlavkoPekaric** [comment]
Found this thread while googling my own problem which isn't connected to your directly, which happens to be:

Error: Cannot find module 'clone-stats'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/vinyl/index.js:3:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

I started getting this after I updated npm and nodejs, looking into the issue now as I've reverted back and still getting it. Will post the solution in case someone else needs it.

**Comment by SlavkoPekaric** [comment]
Ok, so for me the problem was resolved by clearing the npm cache, the reinstalling the dependancies and Gulp globally. I've read that Gulp installs can fail at times too. Hope it helps.

**Comment by iposton** [comment]
thank you @SlavkoPekaric for posting this solution. I was getting the same error. I did `npm cache clean` and reinstalled dependencies with `npm install` and then ran `npm install -g gulp` again and it worked!
