### ISSUE TITLE
Requirements.txt throws an error

### ISSUE THREAD

**Issue by roydeboys** [brwr/thinkster-django-angular-boilerplate#36]
(thinkster-djangular) C:\Users\tanzzz\Desktop\project>pip install -r requirements.txt
Collecting Django==1.7.1 (from -r requirements.txt (line 1))
  Using cached Django-1.7.1-py2.py3-none-any.whl
Collecting dj-database-url==0.3.0 (from -r requirements.txt (line 2))
  Using cached dj_database_url-0.3.0-py2.py3-none-any.whl
Collecting dj-static==0.0.6 (from -r requirements.txt (line 3))
  Using cached dj-static-0.0.6.tar.gz
Collecting django-appconf==0.6 (from -r requirements.txt (line 4))
  Using cached django-appconf-0.6.tar.gz
Collecting django-compressor==1.4 (from -r requirements.txt (line 5))
  Using cached django_compressor-1.4-py2.py3-none-any.whl
Collecting djangorestframework==3.0.0 (from -r requirements.txt (line 6))
  Using cached djangorestframework-3.0.0.tar.gz
Collecting drf-nested-routers==0.9.0 (from -r requirements.txt (line 7))
  Using cached drf-nested-routers-0.9.0.tar.gz
Collecting gunicorn==19.1.1 (from -r requirements.txt (line 8))
  Using cached gunicorn-19.1.1-py2.py3-none-any.whl
Collecting six==1.8.0 (from -r requirements.txt (line 9))
  Using cached six-1.8.0-py2.py3-none-any.whl
Collecting static3==0.5.1 (from -r requirements.txt (line 10))
  Using cached static3-0.5.1.tar.gz
Collecting wsgiref==0.1.2 (from -r requirements.txt (line 11))
  Using cached wsgiref-0.1.2.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\tanzzz\AppData\Local\Temp\pip-build-a0aopqrw\wsgiref\setup.py", line 5, in <module>
        import ez_setup
      File "C:\Users\tanzzz\AppData\Local\Temp\pip-build-a0aopqrw\wsgiref\ez_setup\__init__.py", line 170
        print "Setuptools version",version,"or greater has been installed."
                                 ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\tanzzz\AppData\Local\Temp\pip-build-a0aopqrw\wsgiref\

**Comment by mastertracker** [comment]
Hi, thi is still showing error, any update?

**Comment by roydeboys** [comment]
hello there,
I looked upon the requirements.txt file and also tried to exec the file quite a lot of times still there was no hope.I assume the requirements.txt file has some errors due to which its not able to access the links from django database due to which all the files are not getting downloaded and configured

**Comment by nickwwh** [comment]
Hi guys
I encountered the same issue as well. The fix is to simply remove `wsgiref==0.1.2` from `requirements.txt`. See issue #17
